steps:
  - name: 'gcr.io/k8s-skaffold/pack'
    args:
      - 'build'
      - 'gcr.io/$PROJECT_ID/playradarhub-backend'
      - '--builder=gcr.io/buildpacks/builder'
      - '--publish'

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'playradar-backend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/playradarhub-backend'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'

options:
  logging: CLOUD_LOGGING_ONLY
